import Head from "next/head";
import Header from "@/pages/header";
import Hello from "@/pages/hello";
import About from "@/pages/about";
import Project from "@/pages/project";
import Footer from "@/pages/footer";


export default function Home() {
  return (
    <div className="smooth-scroll">
      <Head>
        <title>FunkyFolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="image/png" href="/assets/image.png" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#13762d] to-[#15162c]">
        <Hello />
        <About />
        <Project />
        <Footer />
      </main>
    </div>
  );
}
