import Head from "next/head";
import Link from "next/link";
import Spline from "@splinetool/react-spline";

export default function Home() {
  return (
    <>
      <Head>
        <title>FunkyFolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#13762d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <span className="text-6xl tracking-tighter 2xl:text-8xl text-white">
            Hello, I&apos;m
            <br />
          </span>
          <span className="text-6xl tracking-tighter 2xl:text-8xl text-white">
            <a className="text-green-300">Funky</a>Clonk.
          </span>
          <span className="text-6xl tracking-tighter 2xl:text-8xl text-white">
            Work in progress
          </span>
          <div>
                          <Spline scene="/assets/scene.splinecode" />
          </div>
        </div>
      </main>
    </>
  );
}
